services:
  - type: web
    name: telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python start.py
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_KEY
        sync: false
      - key: ADMIN_USERNAME
        value: CRAZYPANEL1
      - key: ADMIN_USER_ID
        value: 7490634345
      - key: WEBHOOK_URL
        sync: false
      - key: PORT
        value: 10000
      - key: RENDER
        value: "true"
